FROM squidsolutions/bouquet-war

ADD http://openbouquet.io/download/plugins/v4-db-plugin-apachedrill-1.0.0-RELEASE-jar-with-dependencies.jar /opt/squid/bouquet/plugins/v4-db-plugin-apachedrill-1.0.0-RELEASE-jar-with-dependencies.jar
ADD http://openbouquet.io/download/plugins/v4-db-plugin-spark-1.0.0-RELEASE-jar-with-dependencies.jar /opt/squid/bouquet/plugins/v4-db-plugin-spark-1.0.0-RELEASE-jar-with-dependencies.jar
RUN chmod +r /opt/squid/bouquet/plugins/*.jar
