FROM postgres

MAINTAINER bouquet@squidsolutions.com

ADD restore.sql /docker-entrypoint-initdb.d/restore.sql
ADD 2163.dat /docker-entrypoint-initdb.d/2163.dat
ADD 2165.dat /docker-entrypoint-initdb.d/2165.dat
ADD 2167.dat /docker-entrypoint-initdb.d/2167.dat
ADD 2168.dat /docker-entrypoint-initdb.d/2168.dat
ADD 2169.dat /docker-entrypoint-initdb.d/2169.dat
ADD 2171.dat /docker-entrypoint-initdb.d/2171.dat
ADD 2173.dat /docker-entrypoint-initdb.d/2173.dat
ADD 2175.dat /docker-entrypoint-initdb.d/2175.dat
ADD 2177.dat /docker-entrypoint-initdb.d/2177.dat
ADD 2179.dat /docker-entrypoint-initdb.d/2179.dat
ADD 2181.dat /docker-entrypoint-initdb.d/2181.dat
ADD 2183.dat /docker-entrypoint-initdb.d/2183.dat
ADD 2185.dat /docker-entrypoint-initdb.d/2185.dat
ADD 2187.dat /docker-entrypoint-initdb.d/2187.dat
ADD 2189.dat /docker-entrypoint-initdb.d/2189.dat
ADD toc.dat /docker-entrypoint-initdb.d/toc.dat
